[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

#############
# SCROLLING #
#############

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3

########
# FONT #
########

[font]

# Normal font style
normal = { family = "monospace", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 11.25  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true
